- ZXingObjC.xcodeproj/project.pbxproj
- ZXingObjC.xcodeproj/xcshareddata/xcschemes/iOS Framework.xcscheme
- ios-Info.plist
This change allows code written in Swift to leverage the ZXingObjC library. The framework target has the same or more appropriate build settings as the iOS static library target.
The header visibilities for all targets were necessarily updated in order allow a consumer written in Swift to correctly link against the ZXingObjC iOS framework. Previously the set of header visibilities for the target could not be built against due to references in the top-level framework header (ZXingObjC.h) to headers that were Project and not Public visibility.
> Adding an iOS Framework target and fixing header visibilities for all targets.

- ZXingObjC/datamatrix/ZXDataMatrixWriter.m
Calling `[writer encode:string format:kBarcodeFormatDataMatrix width:size.width height:size.height error:&error]` would raise an `NSInvalidArgumentException` - "Can't find a symbol arrangement that matches the message. Data codewords: 5".
This is the same bug as identified [here](https://github.com/zxing/zxing/issues/361) so same fix was applied.
> Removed minSize dimension from data matrix writer.

- ZXingObjC/client/ZXCGImageLuminanceSource.m
Specified 8 as bitsPerComponent because the new image's color space is CGColorSpaceCreateDeviceRGB()
Without this, it fails to create CGContextRef when CGImageGetBitsPerComponent(self.image) has less value than 8.
> Set bitsPerComponent 8 instead of CGImageGetBitsPerComponent

- ZXingObjC.podspec
- ZXingObjC/ZXMultiFormatReader.m
- ZXingObjC/ZXMultiFormatWriter.m
- ZXingObjC/ZXingObjC.h
Include .h and .m files in root class folder into Core subspec
Use preprocessor definitions to compile different components
independently
This enables use of standalone subspec, current implementation only
allows use of default 'All' subspec
Improve file patterns for subspecs with use of **/* where appropriate
Add subspec for PDF417 components
> Enable independent use of subspecs

- ZXingObjC/ZXingObjC.h
- ZXingObjC/core/ZXingObjCCore.h
Hey! 
Thanks for merging #253 earlier.
This is a small follow up. I have notices that some qrcode/multi headers are included in the `core/ZXingObjCCore.h`, but actually those are not necessary and will break the build if only specific subspecs are used, not `All`.
Core component includes 2 files which are actually from qrcode/multi
Since the framework is supposed to be modular, it should be possible to
exclude QRCode module without breaking the Core component.
Also, even though the headers are imported, the qrcore/module classes
are not used anywhere in Core at all. Those are only used in multi format
reader and writer.
> Remove Core module component on QRCode

- ZXingObjC/aztec/detector/ZXAztecDetector.m
- ZXingObjC/datamatrix/decoder/ZXDataMatrixDecodedBitStreamParser.m
Static declaration is necessary for those variables when you need to use the library more then once in a project
> Hid internal file arrays by applying static declaration

- ZXingObjC/client/ZXCapture.m
It crashed for iPhone 4 because the function canSetSessionPreset returned YES for everything even if iPhone 4 doesn't support 1920x1080.
> add input to AVCaptureSession before setting sessionPreset

- ZXingObjC/client/ZXCapture.h
Update for iOS 10 SDK, but this is not compatible with iOS 9 SDK because it doesn't declare `CALayerDelegate` protocol publicly.
> Update for iOS 10 SDK

- ZXingObjC/client/ZXCapture.m
Set AVCaptureSessionPreset1280x720 to sessionPreset if selected target is OS X Framework because OS X can't use AVCaptureSessionPreset1920x1080.
> Fix build error on OS X Framework

- ZXingObjC.podspec
A way to use Core only as subspec and avoid conditions like that:
`#if defined(ZXINGOBJC_AZTEC) || !defined(ZXINGOBJC_USE_SUBSPECS)`
> Use just Core as subspec

- ZXingObjC/client/ZXCapture.m
Make `AVCaptureSessionPreset1280x720` as the default value of sessionPreset.
> Fix a build error when compiling on macOS

- ZXingObjC.xcodeproj/project.pbxproj
- mac-Info.plist
Using [Carthage](https://github.com/Carthage/Carthage), I wasn't able to integrate this framework into a macOS project I was working on due to several issues with code signing and framework paths.
In this PR I have changed the macOS framework structure to be [more standardised](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) and thus overcome these issues by:
- Including an Info.plist
- Changing the versioned folder name to "A" (to overcome [codesigning](http://www.openradar.me/24260778) [errors](https://lists.apple.com/archives/cocoa-dev/2016/Jul/msg00201.html) relating to Xcode's handling of versioned frameworks)
- [Modifying the Framework Search Paths](https://github.com/mailchimp/ChimpKit3/pull/19/commits/12259392 …
> Update macOS framework target

- ZXingObjC/multi/ZXGenericMultipleBarcodeReader.m
this should fix bug #299 - multiple scan with swift is possible after this fix.
> Reference to delegate in multiple reader made strong

- ZXingObjC/client/ZXCGImageLuminanceSource.m
Memory leaked when cropping as there was an additional reference retained when only returning the cropped image.
> fixed memory leak when using crop

- ZXingObjC.xcodeproj/project.pbxproj
Sorry about omitting this in my last PR - discovered this while submitting my app to the Mac App Store.
Whilst the Info.plist for the Mac framework contained the bundle identifier key, the value (`$(PRODUCT_BUNDLE_IDENTIFIER)`) wasn't actually set in the `project.pbxproj` file (as it was for the iOS framework).
This update sets the bundle identifier for the Mac framework target and resolves another potential codesigning issue.
Thanks again! 🎉
> Add Product Bundle Identifier to OS X Framework target

- ZXingObjC/client/ZXCapture.m
Fix crash when trying to switch from back to front camera on iOS. Related to #274.
> Query input device for supported session preset, set session preset before adding input

- README.md
As of https://github.com/TheLevelUp/ZXingObjC/commit/9420f9809a36e96be3a841229e167398be675ce1 the README recommends Carthage over Cocoapods, so to be consistent we should no longer say Cocoapods is the preferred installation method.
> clarify carthage preference in README

- ZXingObjC/client/ZXCapture.m
I encountered this error when trying to use ZXingObjC on iPad. My app crashed with error message suggesting that I should chech for isTorchModeSupported before setting the mode.
> Fix app crashing when running on device without torch

- README.md
- (void)viewDidLoad {
……
CGImageRef image = [[ZXImage imageWithMatrix:result] cgimage];
self.qrcodeImage.image = [UIImage imageWithCGImage:image];
// @error crash invoke
……
}
> DOC update README.md for  CGImageRetain cgimage of ZXImage

- ZXingObjC/client/ZXImage.m
Fixes #380
Recent changes appear to trigger overflow protection code that crashes on latest iOS + devices. Doesn't occur on debug builds, only release. The issue is that components for setting color intensities are declared as int8_t (signed) when they shouldn't be. See linked issue for more explanation, but the fix is to a) declare proper storage type and b) clamp component values to [0.0, 1.0].
> ZXImage crash #380

- README.md
Added CGImageRelease call following CGImageRetain call in the encoding usage example to demonstrate good practice of lowering the reference count of an object after use.
> Added CGImageRelease call in encoding example

- ZXingObjC/core/ZXDecodeHints.h
- ZXingObjC/core/ZXDecodeHints.m
- ZXingObjC/oned/ZXCode128Reader.m
- ZXingObjC/oned/ZXOneDReader.m
At some point in history, this functionality has been deleted and I don't know, why. It is useful in some cases, however.
Additionally, I did some refactoring in connected areas.
> Restore data sign substitution functionality

- ZXingObjC/oned/ZXCode93Reader.m
Ported c1c2fcfbb098d8b2b422415cbbcfe61791556c01
> Fix Code 93 escapes above %F

- ZXingObjC/pdf417/encoder/ZXPDF417HighLevelEncoder.m
- ZXingObjCTests/pdf417/encoder/ZXPDF417EncoderTestCase.m
Ported 060010253c46d8c9d8c54a0aff854e11cdf59f1b
Ported 849f81354c5f73abfde98a12804bdb909f6a9ba8
> Fixed multibyte charset problem when encoding PDF417 with AUTO

- ZXingObjC/core/ZXEncodeHints.h
- ZXingObjC/pdf417/ZXPDF417Writer.m
Ported 53875e4fd37f089f57e5188bcf8f093701b740d2
Needs additional love, cf. #394.
> PDF417Writer shouldn't ignore ERROR_CORRECTION hint

- ZXingObjC.xcodeproj/project.pbxproj
- ZXingObjC/oned/ZXUPCEReader.m
- ZXingObjC/oned/ZXUPCEWriter.m
- ZXingObjCTests/oned/ZXUPCEWriterTestCase.m
Encoding `04046008` was throwing an exception when encoding. However, that is a valid UPCE code according to https://www.upcdatabase.com/checkdigit.asp.
I also added a test that should catch eventual regressions.
> Fix UPCE checksum calculation

- ZXingObjC/ZXMultiFormatReader.h
- ZXingObjC/ZXMultiFormatWriter.h
- ZXingObjC/core/ZXReader.h
- ZXingObjC/core/ZXWriter.h
Corrected the problem by defining the dependencies in each header file. Error received in these headers: "Cannot find protocol declaration for 'NSObject'"
(Cannot use in Swift without using CocoaPods or Carthage.)
> Import Foundation

- ZXingObjC/ZXMultiFormatWriter.m
Hello!
I'm using this project in the Swift app. Since it's not possible to catch Objc exceptions in Swift the app crashes when the provided code doesn't pass some validations, eg. when `itf` code has odd number of digits:
```swift
if (length % 2 != 0) {
[NSException raise:NSInvalidArgumentException format:@"The length of the input should be even"];
}
```
For a nicer compatibility with Swift I added this small wrapper that bridges nicely to swift so a *try catch* block in Swift can actually catch the error and handle it.
The tests are still passing, I was thinking about adding a Swift test target to test this, but it looked like an overkill for this simple fix.
Cheers, lemme know if this is alright!
> Fix swift crash in ZXMultiFormatWriter.m

- ZXingObjC.xcodeproj/project.pbxproj
This small project settings change will allow Carthage users to use ZXing (or frameworks that link to it) in extensions, including widgets.
> Marked as allowed to be used in extensions.

- ZXingObjC/datamatrix/decoder/ZXDataMatrixDecodedBitStreamParser.m
This PR fixes the interpretation of FNC1 characters (and others) in TEXT and C40 blocks.
This bug is genuine to the iOS port and caused by the different semantics of `Array.length` in Java and `sizeof(array)` in Objective-C (for technical details see the commit message). 
The bug occured in examples of russian cryptocodes (obligatory Datamatrix codes for pharmaceuticals in Russia), which appear to have FNC1 characters in the content. 
It might be advisable to check for other incorrect usages of sizeof in the codebase.
> fix decoding of special characters in TEXT and C40 blocks
